#!/bin/bash


echo "============================================
WIFI SON study
ACAP Survey- Ruckus



============================================

"
read -p "edit?(y/n)" yn

if [ "$yn" ==  "y" ]; then
    vim ~/.mycmds/todo
fi
